# Generated by Django 2.1.4 on 2019-01-15 10:39

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=1000)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('geo', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('country', models.CharField(max_length=2)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('housenumber', models.CharField(blank=True, max_length=10)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('amenity', models.CharField(blank=True, max_length=255)),
                ('version', models.IntegerField(default=0)),
                ('tags', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'amenity',
                'verbose_name_plural': 'amenities',
            },
        ),
    ]
