# Generated by Django 3.0.8 on 2020-07-23 15:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_amenities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='topics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
