# Generated by Django 3.0.8 on 2020-07-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_amenities', '0002_amenity_topics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amenity',
            old_name='amenity',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
